[package]
name = "proptest"
version = "0.3.4"
authors = ["Jason Lingle"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/altsysrq/proptest"
documentation = "https://docs.rs/proptest"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]

description = """
Hypothesis-like property-based testing and shrinking.
"""

[badges]
travis-ci = { repository = "AltSysrq/proptest" }

[features]

default = []

# Enables unstable features of Rust.
unstable = []

[dependencies]
bit-set = "0.4.0"
quick-error = "1.2.1"
rand = "0.3.18"
regex-syntax = "0.4.1"
lazy_static = "0.2.8"

[dev-dependencies]
regex = "0.2.2"
