[package]
name = "proptest"
version = "0.4.2"
authors = ["Jason Lingle"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/altsysrq/proptest"
documentation = "https://docs.rs/proptest"
keywords = ["property", "testing", "quickcheck", "fuzz", "hypothesis"]
categories = ["development-tools::testing"]

description = """
Hypothesis-like property-based testing and shrinking.
"""

[badges]
travis-ci = { repository = "AltSysrq/proptest" }

[features]

default = []

# Enables unstable features of Rust.
unstable = ["rand/i128_support"]

[dependencies]
bitflags = ">=1.0.1"
bit-set = ">=0.4.0"
quick-error = ">=1.2.1"
rand = ">=0.4.2"
regex-syntax = ">=0.4.2"
lazy_static = ">=1.0.0"

[dev-dependencies]
regex = ">=0.2.5"
